### ISSUE TITLE
Update Ubuntu

### ISSUE THREAD

**Issue by waldoj** [openva/richmondsunlight.com#123]
The server is running Ubuntu 12.04.5. I'd like to take it up to 16.10, but I'm not sure what might break. Perform a test deployment, upgrade, see what happens. Then script the deployment, so this never needs to be done manually again.

### Punch List
- [x] test out `cerbot --noninteractive` and settle on correct command
- [x] identify why this process doesn't yield HTTP/2 responses
- [x] solve problem of jQuery UI not installing properly
- [x] solve problem of `jQuery-Tags-Input` not installing at all via npm
- [x] enable mod_pagespeed
- [x] set permissions of site directory to not require root
- [x] create `cache/`, ensure Apache can write to it

**Comment by waldoj** [comment]
Turns out things run fine on PHP v5.6.

**Comment by waldoj** [comment]
I see no reason that this will be problematic. It'll be necessary to use a third-party repo for PHP 5.6, but that's it.

**Comment by waldoj** [comment]
AFAIK, these are the required packages:

`apache2, apache2-mpm-prefork, apache2-utils, apache2.2-bin, apache2.2-common, codedeploy-agent, curl, geoip-database, git, gzip, imagemagick, imagemagick-common, memcached, mod-pagespeed-stable, mysql-client-5.5, mysql-client-core-5.5, mysql-common, openssl, php-apc, php-pear, php5, php5-cgi, php5-cli, php5-common, php5-curl, php5-dev, php5-memcached, php5-mysql, python, python-pip, s3cmd, sphinxsearch, sqlite3, wget`

**Comment by waldoj** [comment]
Also:

* [ ] Apache's enmod list
* [ ] VirtualHost files
* [ ] anything required for Let's Encrypt (which is nothing, I think)
* [ ] any cron jobs not already in another deploy process

**Comment by waldoj** [comment]
```
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -y apache2 apache2-mpm-prefork apache2-utils apache2.2-bin apache2.2-common codedeploy-agent curl geoip-database git gzip imagemagick imagemagick-common memcached mod-pagespeed-stable mysql-client-5.5 mysql-client-core-5.5 mysql-common openssl php-apc php-pear php5 php5-cgi php5-cli php5-common php5-curl php5-dev php5-memcached php5-mysql python python-pip s3cmd sphinxsearch sqlite3 wget
```

**Comment by waldoj** [comment]
Apache config file:

```
<VirtualHost *:443>
  ServerName richmondsunlight.com
  ServerAlias www.richmondsunlight.com
  DocumentRoot /var/www/richmondsunlight.com/htdocs
  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

**Comment by daniel-barrows** [comment]
I also run Ubuntu and would be willing to test and/or write an installation script if that would be helpful. I'm proficient in bash scripting.

Also, it looks like changing [certbot](https://certbot.eff.org/docs/using.html#certbot-command-line-options) to non-interactive can be done by adding the `--noninteractive` flag and then discovering what additional flags are needed from the error output.

**Comment by waldoj** [comment]
Thank you @daniel-barrows! It'd be great if you'd test out the script when it's done. I think I'm closing in on it here. :)

**Comment by waldoj** [comment]
jQuery UI and npm...boy, I don't know.

**Comment by waldoj** [comment]
Ah, so it turns out that simply enabled HTTP/2 won't do the trick — the MPM `prefork` module won't work with it. MPM is one of those things that I've quietly ignored for two decades now, because it just works. I gather I need to switch from `prefork` to `event`.

**Comment by waldoj** [comment]
```
$ sudo a2dismod mpm_prefork
ERROR: The following modules depend on mpm_prefork and need to be disabled first: php5.6
```

D'oh! So, #240 rears its head again. The code in `master` right now is testing out replacing every `mysql` call with `mysqli`, and that's 95% of what needs to be done to get up to PHP 7.

**Comment by waldoj** [comment]
I put together the above by stepping through the entire install process on a fresh t3.micro instance, and I just did it again, tweaking a few things. I intend to continue this until I get a clean build.

**Comment by waldoj** [comment]
And again. Still not clean (an interactive prompt for grub appeared), but closer.

**Comment by waldoj** [comment]
I just got a clean run. I can't say I've caught all edge cases, but I've got most of them. Now to package this up as a script.

**Comment by waldoj** [comment]
All done! The site has been moved to a new server running Ubuntu 18.04. Phew.
