### ISSUE TITLE
Provide site icons of various sizes

### ISSUE THREAD

**Issue by waldoj** [openva/richmondsunlight.com#250]
Right now we only have a `favicon.ico`, which is pretty old-fashioned for a site that derives most of its traffic from mobile. It'd be good to support [the various dimensions necessary for a progressive web app](https://developers.google.com/web/updates/2015/10/splashscreen). But I only have compressed images. @boboroshi, do you still happen to have the PSDs kicking around for the site design?

**Comment by jathayde** [comment]
I don't know why I didn't see the notification for this when it first was sent. Was just alerted to it today thanks to @jalbertbowden. Will pull request these asap.

**Comment by jathayde** [comment]
@waldoj Looking at the code I'll do more damage than help, so I'll just attach here :) 

[sunlight_icons.zip](https://github.com/openva/richmondsunlight.com/files/2928940/sunlight_icons.zip)

So this includes a lot of different sizes. Feel free to discard what you don't need.

* Favicons in 4 sizes
* Apple app icons (for when someone creates an app from a web page)
* Android icons

header code for Apple icons is documented here: https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

HTML works out roughly:
```
<!-- For IE 11, Chrome, Firefox, Safari, Opera -->
<link rel="icon" type="image/png" href="/favicon-16.png" sizes="16x16" />
<link rel="icon" type="image/png" href="/favicon-32.png" sizes="32x32" />
<link rel="icon" type="image/png" href="/favicon-48.png" sizes="48x48" />
<link rel="icon" type="image/png" href="/favicon-62.png" sizes="62x62" />
<link rel="icon" type="image/png" href="/favicon-192.png" sizes="192x192" />

<!-- Add to Home Screen -->
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="apple-mobile-web-app-title" content="Richmond Sunlight">

<!-- iOS Touch Icons -->
<link rel="apple-touch-icon" type="image/png" href="/apple_touch_icons/apple-touch-icon-76.png" sizes="76x76" />
<link rel="apple-touch-icon" type="image/png" href="/apple_touch_icons/apple-touch-icon-120.png" sizes="120x120" />
<link rel="apple-touch-icon" type="image/png" href="/apple_touch_icons/apple-touch-icon-152.png" sizes="152x152" />
<link rel="apple-touch-icon" type="image/png" href="/apple_touch_icons/apple-touch-icon-180.png" sizes="180x180" />

<!-- Safari Pinned Site -->
<link rel="mask-icon" href="safari_icon.svg" />
```

**Comment by jalbertbowden** [comment]
i want to say this is in `new.inc.php` but I don't see any changes on save + refresh. thanks a lot @jathayde!

**Comment by waldoj** [comment]
Yes, the increasingly-badly-named `new.inc.php`.

Thank you, @jathayde! I'll merge those in and set up image names / structures accordingly. It should be a simple PR, now that you've done the real work. :) I appreciate it!

**Comment by waldoj** [comment]
Oh, and the reason you don't see any changes on save + refresh is totally non-obvious: the template is cached in Memcached! Memcached is expired on each _deploy,_ but it hadn't occurred to me that that's totally useless for _local_ development. I've just opened #307 to address that. Thanks for raising this, @jalbertbowden, before I wound up spending 20 minutes confused by it. :)

**Comment by waldoj** [comment]
Yay, all set — thanks, John!
