### ISSUE TITLE
CORS Issue on 404.

### ISSUE THREAD

**Issue by jalbertbowden** [openva/richmondsunlight.com#292]
Getting a CORS issue trying to return the 404/error message:
https://bowdenweb.com/virginia/richmond/richmond-sunlight-api-detect-error-message.html

![richmond-sunlight-api-404-response-cors-issue-screenshot-dev-console](https://user-images.githubusercontent.com/46432/51433449-34138c80-1c18-11e9-93bf-f483fa1eab65.png)

This may sound odd, so please tell me if this is ridiculous/not possible.  

The idea is to detect the error/error response and then act accordingly for the user's benefit/ux. AKA, return a response exactly how a valid API call functions, except the response is an actionable, meaningful, and understandable to the end user.

**Comment by waldoj** [comment]
Happy six month anniversary of this issue! I'm pushing out a fix now. :)

**Comment by jalbertbowden** [comment]
marvelous!
