### ISSUE TITLE
Display legislators' bill notes on the bill pages

### ISSUE THREAD

**Issue by waldoj** [openva/richmondsunlight.com#394]
When legislators create an account on the site, and create a portfolio that includes their own legislation, it stands to reason that any notes that they create about bills should be elevated above the fray. That is, it's a chance for the legislator to say "this is what I have to say in support of this legislation," and that should be displayed front and center.

- [x] Check all Photosynthesis notes to see if any of them is from the legislator who is the chief patron of this bill
- [x] If one of them is from the patron, instead of displaying it inline with the others, instead inject it up top, right after the bill's description

**Comment by waldoj** [comment]
I have no way to test this until a legislator actually signs up for this.

**Comment by carterdacat** [comment]
You could emulate your self as a legislator @waldoj
